#:kivy 1.1.1

<Piece>:
	size: 50, 50
	canvas:
		Ellipse:
			pos: 0,0
			
			


<connect4Game>:
	canvas:
		Ellipse:
			pos: self.center_x-5, 0
		Color:
			rgb: (0,0,0)
		Rectangle:
			pos : (100, 100)
			

	Label:
        font_size: 70  
        center_x: root.width / 4
        top: root.top - 50
        text: "0"
        
    Label:
        font_size: 70  
        center_x: root.width * 3 / 4
        top: root.top - 50
        text: "0"
	Piece:
		id: piece
